<a href="https://colab.research.google.com/github/FadilJalal/Crave/blob/main/SQL_R_Analysis_NorthStar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
install.packages("sqldf")
install.packages("ggplot2")
install.packages("dplyr")

library(sqldf)
library(ggplot2)
library(dplyr)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [6]:
data <- read.csv("deliveries.csv")

head(data)

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at      delivery_status route_distance_km
1 2024-06-19 09:05:59.904311 Failed          17.26
2 2025-01-11 17:39:00.000000 OnTime          10.34
3 2025-06-02 21:45:32.366770 OnTime           7.92
4 2024-03-09 23:30:08.103702 Delayed         16.42
5 2025-09-21 15:45:34.131056 OnTime          14.52
6 2024-09-12 17:11:52.384869 Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22
6 1.57                           9.58

In [7]:
library(sqldf)

sqldf("
SELECT *
FROM data
LIMIT 5
")

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
  delivery_completed_at      delivery_status route_distance_km
1 2024-06-19 09:05:59.904311 Failed          17.26
2 2025-01-11 17:39:00.000000 OnTime          10.34
3 2025-06-02 21:45:32.366770 OnTime           7.92
4 2024-03-09 23:30:08.103702 Delayed         16.42
5 2025-09-21 15:45:34.131056 OnTime          14.52
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22

In [8]:
colnames(data)

 [1] "delivery_id"                   "order_id"
 [3] "driver_id"                     "vehicle_id"
 [5] "hub_id"                        "dispatch_time"
 [7] "delivery_completed_at"         "delivery_status"
 [9] "route_distance_km"             "manual_route_override_count"
[11] "proof_of_completion_missing"   "customer_rating_post_delivery"
[13] "fuel_or_charge_cost"